name: Scorecard supply-chain security

on:
  branch_protection_rule:
  pull_request:
  push:
    branches: [ $default-branch ]
  schedule:
    - cron: "0 8 * * 1" # weekly check

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    if: github.event.repository.default_branch == github.ref_name || github.event_name == 'pull_request'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run analysis (OpenSSF Scorecard)
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        continue-on-error: true
        with:
          results_file: results.json
          results_format: json # keep as JSON
          publish_results: false # still publishes to Security tab

      - name: Show Score
        run: |
          score=$(jq '.score' results.json)
          echo "Score is: $score"

      - name: Upload artifact (scorecard results)
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: scorecard-results
          path: results.json
